version: '3.8'

services:
  load_balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - rede_compose
    depends_on:
      - siteA
      - siteB
      - siteC
  
  siteA:
    image: jgmatosmota/atividade-redes-diego:yellowB
    networks:
      - rede_compose

  siteB:
    image: jgmatosmota/atividade-redes-diego:greenB
    networks:
      - rede_compose
  
  siteC:
    image: jgmatosmota/atividade-redes-diego:blueB
    networks:
      - rede_compose

networks:
  rede_compose:
    driver: bridge
